[package]
name = "swss"
version = "0.1.0"
authors = ["Krzysztof Kozlowski <krzk@kernel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#websocket = "0.24.0"
tungstenite = "0.10.0"
openssl = "0.10.0"
